// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model;

#nullable disable

namespace EFEksamensTest.Migrations
{
    [DbContext(typeof(StudioContext))]
    [Migration("20240617145624_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Model.Actor", b =>
                {
                    b.Property<int>("ActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FilmId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Køn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ActorId");

                    b.HasIndex("FilmId");

                    b.ToTable("Actor");
                });

            modelBuilder.Entity("Model.Film", b =>
                {
                    b.Property<int>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beskrivelse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StudioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FilmId");

                    b.HasIndex("StudioId");

                    b.ToTable("Film");
                });

            modelBuilder.Entity("Model.Studio", b =>
                {
                    b.Property<int>("StudioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudioId");

                    b.ToTable("Studios", (string)null);
                });

            modelBuilder.Entity("Model.Actor", b =>
                {
                    b.HasOne("Model.Film", null)
                        .WithMany("Actors")
                        .HasForeignKey("FilmId");
                });

            modelBuilder.Entity("Model.Film", b =>
                {
                    b.HasOne("Model.Studio", null)
                        .WithMany("Films")
                        .HasForeignKey("StudioId");
                });

            modelBuilder.Entity("Model.Film", b =>
                {
                    b.Navigation("Actors");
                });

            modelBuilder.Entity("Model.Studio", b =>
                {
                    b.Navigation("Films");
                });
#pragma warning restore 612, 618
        }
    }
}
